;[
  {
    'Accept-Ranges': 'bytes',
    'Cache-Control': 'no-cache, must-revalidate',
    Connection: 'Keep-Alive',
    'Content-Encoding': 'gzip',
    'Content-Language': 'en',
    'Content-Length': '7890',
    'Content-Type': 'text/html; charset=utf-8',
    Date: 'Sat, 08 Jun 2024 05:07:49 GMT',
    ETag: '"1534-599f6c72a5c80-gzip"',
    Expires: 'Sun, 19 Nov 1978 05:00:00 GMT',
    'Keep-Alive': 'timeout=15, max=100',
    'Last-Modified': 'Wed, 18 Dec 2019 09:07:46 GMT',
    Link:
      '<https://itsecgames.com/>; rel="canonical",<https://itsecgames.com/>; rel="shortlink"',
    Server: 'Apache',
    Vary: 'Accept-Encoding',
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'SAMEORIGIN',
    'X-Generator': 'Drupal 7 (http://drupal.org)',
    'X-UA-Compatible': 'IE=edge',
    'accept-ranges': 'bytes',
    'access-control-allow-credentials': 'true',
    'access-control-allow-origin': '*',
    age: '1203',
    'content-security-policy-report-only':
      "require-trusted-types-for 'script'; report-uri https://csp.withgoogle.com/csp/apps-themes",
    'cross-origin-opener-policy': 'same-origin-allow-popups',
    'cross-origin-resource-policy': 'cross-origin',
    expires: 'Sat, 08 Jun 2024 05:07:49 GMT',
    'last-modified': 'Sat, 08 Jun 2024 05:07:49 GMT',
    link: '<https://fonts.gstatic.com>; rel=preconnect; crossorigin',
    'opc-request-id':
      '/FB21F01164D45FFB0F18F2D9559FBBAC/90A8B063F16F648805215FA646E6D1D6',
    'report-to':
      '{"group":"apps-themes","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/apps-themes"}]}',
    server: 'Oracle API Gateway',
    'strict-transport-security': 'max-age=31536000',
    'timing-allow-origin': '*',
    vary: 'Accept-Encoding',
    'x-content-type-options': 'nosniff',
    'x-distribution': '99',
    'x-frame-options': 'sameorigin',
    'x-host': 's7.addthis.com',
    'x-xss-protection': '1; mode=block',
  },
  {
    issuer_name: 'R3',
    issuer_org: "Let's Encrypt",
    issuer_org_unit: '',
    subject_name: 'mmebv.be',
    subject_org: '',
    subject_org_unit: '',
    subject_country: '',
    subject_post_code: '',
    subject_street_address: '',
    subject_alt_names: [
      'mmebv.be',
      'mmebv.com',
      'mmebvba.com',
      'mmesec.be',
      'mmesec.com',
      'www.mmebv.be',
      'www.mmebv.com',
      'www.mmebvba.com',
      'www.mmesec.be',
      'www.mmesec.com',
    ],
    authority_key_id: '142eb317b75856cbae500940e61faf9d8b14c2c6',
    algorithm: 'SHA256-RSA',
    version: 3,
    not_before: 1713002383,
    not_after: 1720778382,
    days_left: 34,
    public_key_alg: 'RSA',
    public_key_size: 2048,
    is_leaf: true,
  },
  {
    target_url: 'https://itsecgames.com',
    target_hostname: 'itsecgames.com',
    target_subdomain: '',
    page_accessed: [],
    page_redirects: [],
    anchor_links: [],
    script_links: [],
    image_links: [],
    css_links: [],
    fav_icon_links: [],
    video_links: [],
    manifest_links: [],
  },
  {
    target: 'itsecgames.com',
    os_matches: [],
    ports: [
      {
        port_id: 22,
        state: 'open',
        service: 'ssh',
        script_output: '',
      },
      {
        port_id: 80,
        state: 'open',
        service: 'http',
        script_output: '',
      },
      {
        port_id: 443,
        state: 'open',
        service: 'https',
        script_output: '',
      },
    ],
    online: true,
  },
]
